import { Product } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Pro Match Jersey',
    price: 699,
    originalPrice: 999,
    description: 'Tournament-grade sublimation jersey with moisture control.',
    longDescription: 'Built for the pitch. Our Pro Match Jersey uses advanced sublimation printing that never fades, peels, or cracks. The lightweight polyester mesh keeps you cool under pressure. Available with full custom name, number, and team badge printing. Minimum order 10 jerseys.',
    images: ['https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800'],
    category: 'jerseys',
    sport: 'football',
    tags: ['jersey', 'match', 'sublimation', 'custom'],
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Custom'],
    customizable: true,
    moq: 10,
    featured: true,
    isNew: false,
  },
  {
    id: '2',
    name: 'Elite Training Kit',
    price: 1199,
    description: 'Full jersey + shorts combo for serious training sessions.',
    longDescription: 'The Elite Training Kit bundles our performance jersey with matching shorts. Four-way stretch fabric moves with your body. Full sublimation custom printing available for teams.',
    images: ['https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800'],
    category: 'jerseys',
    sport: 'football',
    tags: ['kit', 'training', 'jersey', 'shorts', 'combo'],
    rating: 4.8,
    reviewCount: 189,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Custom'],
    customizable: true,
    moq: 5,
    featured: true,
    isNew: true,
  },
  {
    id: '3',
    name: 'Goalkeeper Kit',
    price: 849,
    description: 'Padded goalkeeper jersey with grip shorts.',
    longDescription: 'Purpose-built for goalkeepers. Foam padding on elbows and hips protects during dives. Custom name and number printing included.',
    images: ['https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=800'],
    category: 'jerseys',
    sport: 'football',
    tags: ['goalkeeper', 'kit', 'padded', 'custom'],
    rating: 4.7,
    reviewCount: 94,
    inStock: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Custom'],
    customizable: true,
    moq: 1,
    featured: false,
    isNew: true,
  },
  {
    id: '4',
    name: 'Club Tracksuit',
    price: 1499,
    description: 'Warm-up tracksuit with custom club embroidery.',
    longDescription: 'Look sharp on and off the pitch. Club name and crest embroidery available on chest and thigh. Made from anti-pill fleece.',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800'],
    category: 'jerseys',
    sport: 'football',
    tags: ['tracksuit', 'warmup', 'club', 'embroidery'],
    rating: 4.8,
    reviewCount: 142,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black/Red', 'Black/White', 'Navy/Gold'],
    customizable: true,
    moq: 5,
    featured: true,
    isNew: false,
  },
  {
    id: '5',
    name: 'Nike Mercurial Vapor',
    price: 8999,
    originalPrice: 11999,
    description: 'Speed boots with Flyknit upper and ACC technology.',
    longDescription: 'The Nike Mercurial Vapor is built for pure speed. Flyknit upper wraps your foot for a second-skin fit. ACC (All Conditions Control) rubber ensures grip in wet and dry conditions. Conical studs for explosive acceleration.',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'],
    category: 'shoes',
    sport: 'football',
    tags: ['boots', 'nike', 'speed', 'mercurial'],
    rating: 4.9,
    reviewCount: 445,
    inStock: true,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Volt/Black', 'Blue/Silver', 'Red/Black'],
    customizable: false,
    featured: true,
    isNew: false,
  },
  {
    id: '6',
    name: 'Adidas Predator Elite',
    price: 9499,
    description: 'Control boots with Controlframe outsole.',
    longDescription: 'The Adidas Predator Elite gives you total control. The Controlskin upper grips the ball in all conditions. Laceless design for a clean striking surface. Controlframe outsole delivers stability and traction.',
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800'],
    category: 'shoes',
    sport: 'football',
    tags: ['boots', 'adidas', 'predator', 'control'],
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Black/White', 'Red/Black'],
    customizable: false,
    featured: true,
    isNew: true,
  },
  {
    id: '7',
    name: 'Puma Future 7',
    price: 7499,
    description: 'Adaptive fit boots with FUZIONFIT+ compression band.',
    longDescription: 'The Puma Future 7 Elite adapts to your foot with FUZIONFIT+ compression band technology. The RAPIDAGILITY outsole is engineered for quick changes of direction.',
    images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800'],
    category: 'shoes',
    sport: 'football',
    tags: ['boots', 'puma', 'future', 'adaptive'],
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Yellow/Black', 'Blue/Pink'],
    customizable: false,
    featured: false,
    isNew: true,
  },
  {
    id: '8',
    name: 'Custom Name & Number',
    price: 150,
    description: 'Add your name and number to any jersey.',
    longDescription: 'Get your player name and number printed on any jersey using premium sublimation or heat-press technology. Choose your font style and color. Available for single pieces — no minimum order.',
    images: ['https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800'],
    category: 'customization',
    sport: 'football',
    tags: ['custom', 'name', 'number', 'printing'],
    rating: 5.0,
    reviewCount: 892,
    inStock: true,
    sizes: ['One Size'],
    colors: ['Any Color'],
    customizable: true,
    moq: 1,
    featured: true,
    isNew: false,
  },
  {
    id: '9',
    name: 'Club Badge Printing',
    price: 299,
    description: 'Your club logo sublimated on any garment.',
    longDescription: 'Upload your club badge and we will sublimate it onto any jersey, tracksuit, or polo. Full color, photographic quality. Lasts the lifetime of the garment. Available for single pieces or bulk orders.',
    images: ['https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800'],
    category: 'customization',
    sport: 'football',
    tags: ['badge', 'logo', 'club', 'sublimation'],
    rating: 4.9,
    reviewCount: 456,
    inStock: true,
    sizes: ['Small', 'Medium', 'Large'],
    colors: ['Full Color'],
    customizable: true,
    moq: 1,
    featured: false,
    isNew: false,
  },
  {
    id: '10',
    name: 'Full Team Kit Package',
    price: 4999,
    originalPrice: 6999,
    description: 'Complete custom kit for 11 players — jersey, shorts & socks.',
    longDescription: 'The ultimate team package. Includes 11 custom sublimated jerseys with player names and numbers, matching shorts, and socks. Your club badge and sponsor logo included. Delivered in 10 days.',
    images: ['https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800'],
    category: 'customization',
    sport: 'football',
    tags: ['team', 'package', 'full kit', 'bulk', 'custom'],
    rating: 5.0,
    reviewCount: 234,
    inStock: true,
    sizes: ['Mixed'],
    colors: ['Custom'],
    customizable: true,
    moq: 11,
    featured: true,
    isNew: false,
  },
  {
    id: '11',
    name: 'Adidas Tiro Training Ball',
    price: 1299,
    description: 'Durable training ball with machine-stitched panels.',
    longDescription: 'The Adidas Tiro Training Ball is built for daily use. Machine-stitched for durability and consistent performance. Butyl bladder retains air for long-lasting shape. Available in sizes 3, 4, and 5.',
    images: ['https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800'],
    category: 'balls',
    sport: 'football',
    tags: ['ball', 'adidas', 'training', 'tiro'],
    rating: 4.6,
    reviewCount: 567,
    inStock: true,
    sizes: ['Size 3', 'Size 4', 'Size 5'],
    colors: ['White/Black', 'White/Red'],
    customizable: false,
    featured: false,
    isNew: false,
  },
  {
    id: '12',
    name: 'Nike Premier League Ball',
    price: 2499,
    originalPrice: 3499,
    description: 'Match ball with Nike Aerowtrac grooves.',
    longDescription: 'The official Nike Premier League match ball. Aerowtrac grooves give you predictable flight and trajectory. Reinforced rubber bladder for consistent air retention. Hand-stitched panels for pro-level feel.',
    images: ['https://images.unsplash.com/photo-1552667466-07770ae110d0?w=800'],
    category: 'balls',
    sport: 'football',
    tags: ['ball', 'nike', 'match', 'premier league'],
    rating: 4.8,
    reviewCount: 334,
    inStock: true,
    sizes: ['Size 5'],
    colors: ['White/Red/Blue'],
    customizable: false,
    featured: true,
    isNew: false,
  },
]

export const categories = [
  { id: 'jerseys', name: 'Jerseys & Kits', icon: '👕', color: 'from-red-500/20 to-red-900/10' },
  { id: 'shoes', name: 'Football Boots', icon: '👟', color: 'from-orange-500/20 to-orange-900/10' },
  { id: 'customization', name: 'Customization', icon: '✨', color: 'from-yellow-500/20 to-yellow-900/10' },
  { id: 'balls', name: 'Footballs', icon: '⚽', color: 'from-green-500/20 to-green-900/10' },
]

export const getFeatured = () => products.filter((p) => p.featured)
export const getById = (id: string) => products.find((p) => p.id === id)
export const getByCategory = (cat: string) => products.filter((p) => p.category === cat)

export const testimonials = [
  { name: 'Rahul Patil', club: 'FC Deccan Warriors', text: 'Quality is outstanding. Our entire team is in GS kits now. The sublimation print hasn\'t faded even after 60 washes.', rating: 5 },
  { name: 'Suresh Jadhav', club: 'Pune City FC', text: 'Ordered 25 jerseys with custom name/numbers. Delivered in 10 days, perfect stitching, exactly what we wanted.', rating: 5 },
  { name: 'Amitesh Kulkarni', club: 'Hadapsar United', text: 'Best sports kit supplier in Pune. Prices are fair, quality is premium. GS Sports is the real deal.', rating: 5 },
  { name: 'Vikram Shinde', club: 'Kothrud FC', text: 'The goalkeeper kit is excellent. Padding is well placed, colors are bright, and delivery was on time.', rating: 5 },
]